version: "3.7"
 
services:
 
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.6.0"
    environment:
      discovery.type: "single-node"
      cluster.name: "cluster-1"
      node.name: "node-1"
      xpack.security.enabled: false
    ports:
      - "9200:9200"
    volumes:
      - "./tmp/elasticsearch/data:/usr/share/elasticsearch/data"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
  elastichq:
    image: "elastichq/elasticsearch-hq"
    ports:
      - "5000:5000"
    depends_on:
      - "elasticsearch"
 
  cerebro:
    image: "lmenezes/cerebro"
    ports:
      - "9000:9000"
    depends_on:
      - "elasticsearch"